# Generated by Django 5.0.6 on 2025-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
        migrations.AddField(
            model_name='hall',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
